### ISSUE TITLE
Config files from nested folders

### ISSUE THREAD

**Issue by Aarkon** [adam-gaia/new-stow#1]
Greetings!

I have a dotfiles-repo roughly looking like this:

```
├── machineA
│   ├── stowfile
│   └── sway
│       └── config
├── helix
│   ├── config.toml
│   └── languages.toml
├── machineB
│   ├── stowfile
│   └── sway
│       └── config
├── machineC
│   └── stowfile
└── README.md
```

What doesn't work is stowing the `machine{A,B}/sway/config` files: 

```
---

stow:
  - src: ../helix/config.toml
    links:
      - "${HOME}/.config/helix/config.toml"

  - src: ../helix/languages.toml
    links:
      - "${HOME}/.config/helix/languages.toml"

  - sway:
    - src: config
      links:
        - "${HOME}/.config/sway/config"
  
  - src: ../.zshrc
    links:
      - "${HOME}/.zshrc" 
```
This gives me: `Error: Source file "/home/aarkon/src/dotfiles/machineA/../helix/../helix/sway/config.conf" does not exist" does not exist`. Without having looked at your code, I suggest the reason is that the path to the `sway/config` file gets wrongly extended. If you could fix that, I'd be an even more happy user of your nice tool :smiley:
